# Generated by Django 4.0.2 on 2022-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studprofile',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studprofile',
            name='emaill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studprofile',
            name='studId',
            field=models.CharField(max_length=10),
        ),
    ]
