# Generated by Django 4.0.2 on 2022-09-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_studprofile_done_studprofile_emaill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
