# Generated by Django 4.0.2 on 2022-09-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_studprofile_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='', upload_to='profile_images')),
                ('des', models.TextField(blank=True)),
                ('admin1', models.CharField(blank=True, max_length=100)),
                ('admin2', models.CharField(blank=True, max_length=100)),
                ('admin3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
