# Generated by Django 4.0.2 on 2022-09-17 02:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_name_studprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('venue', models.CharField(max_length=1000)),
                ('deadLine', models.DateTimeField(default=datetime.datetime.now)),
                ('des', models.TextField(blank=True)),
            ],
        ),
    ]
