# Generated by Django 4.0.2 on 2022-09-17 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_posts_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='deadLine',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
