# Generated by Django 4.0.2 on 2022-09-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_posts_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studprofile',
            name='course',
        ),
    ]
