# Generated by Django 4.0.2 on 2022-09-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_remove_studprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studprofile',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
