# Generated by Django 4.0.2 on 2022-09-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_studprofile_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studprofile',
            old_name='studId',
            new_name='regId',
        ),
    ]
