# Generated by Django 4.0.2 on 2022-09-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_rename_studid_studprofile_regid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='cntemail',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='imagee',
        ),
        migrations.AddField(
            model_name='posts',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='des',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='venue',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
