# Generated by Django 4.0.2 on 2022-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_studprofile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagee',
            field=models.ImageField(default='img-01.png', upload_to='post_images'),
        ),
    ]
