# Generated by Django 4.0.2 on 2022-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_posts_imagee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagee',
            field=models.ImageField(default='img-01.png', upload_to='post_images'),
        ),
    ]
